org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.caching.debug=false
org.gradle.configuration-cache=false
org.gradle.configureondemand=true

modId=unchained
modCobblemonVersion=1.8.0
modMyVersion=1.7.1
modName=Unchained
modDescription=What if you were rewarded with boosts to spawns around you when you reached certain Counter stats?
modAuthor=timinc aka Timothy Metcalfe
modIssues=https://github.com/timinc-cobble/cobblemon-unchained/issues
modSource=https://github.com/timinc-cobble/cobblemon-unchained
modDiscord=https://discord.com/invite/WKAR27SdSv

#mod definitions
archives_base_name=unchained
maven_group=us.timinc.mc.cobblemon

#fabric project dependencies
fabric_loader_version=0.17.2
fabric_api_version=0.116.6+1.21.1
fabric_kotlin=1.13.6+kotlin.2.2.20
graalvm_version=22.3.0
icu4j_version=71.1

#neoforge project dependencies
neoforge_version=21.1.182
kotlin_for_forge_version=5.10.0

#common dependencies
minecraft_version=1.21.1
cobblemon_version=1.8.0+1.21.1
junit_version=5.1.0
tim_core_fabric_version=1.8.0-fabric-1.32.0
tim_core_neoforge_version=1.8.0-neoforge-1.32.0
counter_fabric_version=1.8.0-fabric-1.9.0
counter_neoforge_version=1.8.0-neoforge-1.9.0
